# -*- coding: utf-8 -*-
"""Pattern_Recognition_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cq8ESzkKoa_q7FSg2N6ekZUldt41vz_7
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import stft
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense

# -------------------------------
# STEP 1: Download Data
# -------------------------------
data = yf.download("AAPL", start="2020-01-01", end="2023-01-01")

prices = data['Close'].dropna()
signal = prices.values.flatten()

print("Signal shape:", signal.shape)

# -------------------------------
# STEP 2: Create Sliding Windows
# -------------------------------
window_size = 100

X = []
y = []

for i in range(len(signal) - window_size):
    segment = signal[i:i+window_size]

    # Apply STFT
    f, t, Zxx = stft(segment)

    # Spectrogram
    spec = np.abs(Zxx)

    # Normalize
    spec = spec / np.max(spec)

    X.append(spec)

    # Target = next price
    y.append(signal[i + window_size])

X = np.array(X)
y = np.array(y)

print("X shape before reshape:", X.shape)
print("y shape:", y.shape)

# -------------------------------
# STEP 3: Reshape for CNN
# -------------------------------
X = X.reshape(X.shape[0], X.shape[1], X.shape[2], 1)

print("X shape after reshape:", X.shape)

# -------------------------------
# STEP 4: Build CNN Model
# -------------------------------
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(X.shape[1], X.shape[2], 1)),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

# -------------------------------
# STEP 5: Train Model
# -------------------------------
model.fit(X, y, epochs=10, batch_size=16)

# -------------------------------
# STEP 6: Predict
# -------------------------------
prediction = model.predict(X[-1].reshape(1, X.shape[1], X.shape[2], 1))

print("Predicted next price:", prediction)

# -------------------------------
# STEP 7: Plot Original Prices
# -------------------------------
plt.plot(signal)
plt.title("Stock Price")
plt.show()

# -------------------------------
# STEP 8: Plot Sample Spectrogram
# -------------------------------
plt.pcolormesh(t, f, spec)
plt.title("Sample Spectrogram")
plt.ylabel("Frequency")
plt.xlabel("Time")
plt.show()